using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class NavManager : MonoBehaviour
{

    public static NavManager instance;
    public Room startingRoom;
    public Room currentRoom;

    private void Awake()
    {
        if (instance == null)
            instance = this;
        else
            Destroy(gameObject);
        DontDestroyOnLoad(gameObject);
    }
    // Start is called before the first frame update
    void Start()
    {
        Debug.Log(startingRoom.description);
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}
